### PR TITLE
update dependency to latest

### PR DESCRIPTION
**Pull request by halfcrazy**

### CODE REVIEW

**Comment by greenpau** [comment]
@halfcrazy , why did you close this PR?

**Comment by halfcrazy** [comment]
> @halfcrazy , why did you close this PR?

The previous log lib `github.com/prometheus/common/log` doesn't exist in the new Prometheus version, the new `github.com/prometheus/common/promlog` is not a drop-in replacement, and there's some work to do for the logging related code.

**Comment by greenpau** [comment]
>  and there's some work to do for the logging related code.

@halfcrazy, will work on it.

**Comment by greenpau** [comment]
@halfcrazy , release 1.0.4 with the updated logging. Please test.

Also, could you please help with https://github.com/greenpau/ovs_exporter/issues/3 ?

**Pull request closed without merging**
